In [52]:
import pandas as pd

df_vendas = pd.read_csv('vendas_tech.csv')

C:\Users\hyago\AppData\Local\Temp\ipykernel_38056\42662164.py:3: DtypeWarning: Columns (0: Data_Base) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv('vendas_tech.csv')

In [25]:
df_vendas.columns

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente', 'Data_Base'],
      dtype='str')

In [18]:
df_vendas.index

RangeIndex(start=0, stop=100100, step=1)

In [ ]:
set(df_vendas['Data'])

0         2023-06-08
1         2023-03-01
2         2023-02-25
3         2024-11-19
4         2024-01-27
             ...
100095    2023-10-20
100096    2024-03-17
100097    2023-06-19
100098    2024-06-14
100099    2023-01-03
Name: Data, Length: 100100, dtype: str

In [28]:
df_vendas[['Data', 'Loja']].head()

         Data            Loja
0  2023-06-08       São Paulo
1  2023-03-01  Belo Horizonte
2  2023-02-25             NaN
3  2024-11-19  RIO DE JANEIRO
4  2024-01-27  Rio de Janeiro

In [30]:
# iloc = Index Location
list(df_vendas.iloc[0])
# Lança tudo oque tiver na primeira linha e converte para uma lista

[np.int64(1),
 '2023-06-08',
 'São Paulo',
 'Mouse Gamer',
 np.float64(120.0),
 np.int64(1),
 'Cliente_4095',
 '2025-01-01']

In [ ]:
df_vendas.iloc[10][2] 
# Esta é outra forma de acessar valores dentro da planilha atraves do pandas, o numero no primeiro colchete é referente a linha, e no segundo é referente a coluna. Assim como em um plano carteasiano. Podemos tambem acessar a coluna pelo seu nome dessa forma

# df_vendas.iloc[10]['Data']

In [31]:
df_vendas.head()

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN

In [8]:
# Filtra as linhas em que o valor na coluna 'Produto' Seja 'Cabo HDMI e que o valor na coluna 'Cliente' seja igual a 'Cliente_24809'
df_vendas[(df_vendas['Produto'] == 'Cabo HDMI') & (df_vendas['Cliente'] == 'Cliente_24809')]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN

In [9]:
# Filtra as linhas em que o valor na coluna 'Produto' Seja 'Cabo HDMI OU que o valor na coluna 'Cliente' seja igual a 'Cliente_24809'
df_vendas[(df_vendas['Produto'] == 'Cabo HDMI') | (df_vendas['Cliente'] == 'Cliente_24809')]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
14,15,2023-06-23,Curitiba,Cabo HDMI,40.0,1,Cliente_27383,NaN
17,18,2023-07-06,Curitiba,Cabo HDMI,40.0,1,Cliente_24451,NaN
18,19,2024-03-20,Salvador,Cabo HDMI,40.0,1,Cliente_4793,NaN
23,24,2023-05-15,Recife,Cabo HDMI,40.0,3,Cliente_20951,NaN
...,...,...,...,...,...,...,...,...
100031,36341,2023-06-06,Porto Alegre,Cabo HDMI,40.0,1,Cliente_26931,NaN
100034,39507,2024-04-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_17853,NaN
100038,67181,2023-07-27,Curitiba,Cabo HDMI,40.0,1,Cliente_9674,NaN
100039,64631,2024-07-18,Curitiba,Cabo HDMI,40.0,1,Cliente_8625,NaN
100042,7048,2024-08-25,Recife,Cabo HDMI,40.0,1,Cliente_3840,NaN

In [ ]:
# Mostra somente as linhas em que o valor da coluna Qtd seja maior que 2, tambem podemos usar menos que, diferente de, etc
df_vendas[df_vendas['Qtd'] > 2]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
19,20,2024-08-15,Belo Horizonte,Smartphone Samsung,2200.0,3,Cliente_27943,NaN
23,24,2023-05-15,Recife,Cabo HDMI,40.0,3,Cliente_20951,NaN
26,27,2023-12-15,Curitiba,Teclado Mecânico,250.0,3,Cliente_20985,NaN
29,30,2023-03-18,Recife,iPhone 14,5500.0,5,Cliente_25098,NaN
35,36,2023-08-18,RIO DE JANEIRO,"Monitor 27""",1200.0,10,Cliente_14934,NaN
...,...,...,...,...,...,...,...,...
100071,46177,2024-09-05,Belo Horizonte,Teclado Mecânico,250.0,3,Cliente_20588,NaN
100073,73650,2023-02-07,Curitiba,iPhone 14,5500.0,5,Cliente_24706,NaN
100082,48996,2023-09-13,São Paulo,Notebook Dell,3500.0,5,Cliente_29405,NaN
100089,169,2023-10-10,Recife,Mouse Gamer,120.0,3,Cliente_4407,NaN
100093,77528,2024-03-30,São Paulo,"Monitor 27""",1200.0,3,Cliente_5144,NaN

In [ ]:
# Pega todas as linhas em que o código do cliente termina com o número 6, tambem temos as funções startwith()
df_vendas[df_vendas['Cliente'].str.endswith('6')]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
11,12,2024-01-29,Rio de Janeiro,Mouse Gamer,120.0,1,Cliente_586,NaN
20,21,2024-12-27,Curitiba,Teclado Mecânico,250.0,1,Cliente_20626,NaN
27,28,2024-02-18,Belo Horizonte,Notebook HP,3200.0,1,Cliente_25846,NaN
28,29,2023-04-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_15726,NaN
...,...,...,...,...,...,...,...,...
100065,51102,2023-08-11,Belo Horizonte,iPhone 14,5500.0,2,Cliente_12146,NaN
100066,42101,2023-09-18,São Paulo,Smartphone Samsung,2200.0,2,Cliente_24386,NaN
100067,66012,2023-10-04,Salvador,Mouse Gamer,120.0,1,Cliente_4656,NaN
100073,73650,2023-02-07,Curitiba,iPhone 14,5500.0,5,Cliente_24706,NaN
100090,15752,2023-03-20,Curitiba,"Monitor 27""",1200.0,1,Cliente_356,NaN

In [ ]:
# Filtra todas as linhas que fazem parte das lojas de Belo Horizonte ou do Rio de Janeiro
df_vendas[df_vendas['Loja'].isin(['Belo Horizonte', 'Rio de Janeiro'])]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
11,12,2024-01-29,Rio de Janeiro,Mouse Gamer,120.0,1,Cliente_586,NaN
13,14,2023-04-13,Belo Horizonte,Smartphone Samsung,2200.0,1,Cliente_22985,NaN
...,...,...,...,...,...,...,...,...
100071,46177,2024-09-05,Belo Horizonte,Teclado Mecânico,250.0,3,Cliente_20588,NaN
100077,23741,2023-06-13,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8627,NaN
100081,95553,2023-09-15,Belo Horizonte,iPhone 14,5500.0,1,Cliente_4987,NaN
100083,52708,2023-09-17,Rio de Janeiro,iPhone 14,5500.0,1,Cliente_10137,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN

In [ ]:
# Aqui fazemos o contrario do bloco anterior, estamos verificando somente as linhas de lojas que NÃO sao de Belo Horizonte ou do Rio de Janeiro
df_vendas[~df_vendas['Loja'].isin(['Belo Horizonte', 'Rio de Janeiro'])]

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
...,...,...,...,...,...,...,...,...
100094,32853,2024-04-10,Salvador,Smartphone Samsung,2200.0,2,Cliente_29799,NaN
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

In [ ]:
# LOC = Locate Based on Label. Esse código localiza as linhas em que o cliente tem o código Cliente_3274
df_vendas.loc[df_vendas['Cliente'] == 'Cliente_3274']

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
32931,32932,2023-05-05,Porto Alegre,Cabo HDMI,40.0,1,Cliente_3274,NaN
36754,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN
39227,39228,2024-04-12,Belo Horizonte,Teclado Mecânico,250.0,1,Cliente_3274,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

In [ ]:
# Este código, primeiro localiza a linha especifica com o nome do Cliente, e troca pelo seu Nome dele
df_vendas.loc[df_vendas['Cliente'] == 'Cliente_3274', 'Cliente'] = 'Lucio'

In [17]:
df_vendas.loc[df_vendas['Cliente'] == 'Lucio']

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
32931,32932,2023-05-05,Porto Alegre,Cabo HDMI,40.0,1,Lucio,NaN
36754,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Lucio,NaN
39227,39228,2024-04-12,Belo Horizonte,Teclado Mecânico,250.0,1,Lucio,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Lucio,NaN

In [37]:

# Transforma os textos com letras todas em maiusculo ou todas em minuculo para somente a primeira letra em maiuscula
# cidade = 'Belo Horizonte'
# df_vendas.loc[(df_vendas['Loja'] == cidade.lower()) | (df_vendas['Loja'] == cidade.upper()), 'Loja'] = cidade

# Uma forma mais simples e melhor de fazer isso, é usando o comando .str.title(), que já faz isso manualmente
df_vendas['Loja'] = df_vendas['Loja'].str.title()

In [38]:
df_vendas

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Lucio,NaN

In [53]:
df_vendas = df_vendas.drop(columns=['Data_Base'])

In [54]:
df_vendas.tail()

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

In [ ]:
df_vendas.dropna()
df_vendas.fillna({'Qtd':0}, inplace=True)

In [55]:
df_vendas.rename(columns={'Qtd': 'Qnt'})
df_vendas

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

In [56]:
df_vendas['Cliente'].value_counts()

Cliente
Cliente_28700    12
Cliente_19548    11
Cliente_4582     11
Cliente_27735    11
Cliente_5799     11
                 ..
Cliente_22226     1
Cliente_13227     1
Cliente_22372     1
Cliente_28772     1
Cliente_23892     1
Name: count, Length: 28896, dtype: int64

In [57]:
df_vendas.groupby('Cliente')['Qtd'].sum()

Cliente
Cliente_1         3
Cliente_10        2
Cliente_100       2
Cliente_1000      4
Cliente_10000     8
                 ..
Cliente_9995      1
Cliente_9996      8
Cliente_9997     12
Cliente_9998     10
Cliente_9999      5
Name: Qtd, Length: 28896, dtype: int64

In [ ]:
df_vendas.to_excel('new_file', index=False)

ValueError: No engine for filetype: 'xlxx'